name: '🙏 Feature request'
description: Suggest a new feature for this project
labels: ['💡 feature', '👀 needs triage']

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!

  - type: textarea
    id: what-happened
    validations:
      required: true
    attributes:
      label: Current behavior
      description: Is your feature request related to a problem? Please describe.

  - type: textarea
    id: suggested-solution
    validations:
      required: false
    attributes:
      label: Suggested solution
      description: Describe the solution you'd like.

  - type: input
    id: context
    attributes:
      label: Additional context
      description: Add any other context about the problem or helpful links here.
